#!/bin/bash

CURRENT_DIR=${BASH_SOURCE%/*}

FIXTURE=laravel5.5 LARAVEL_VERSION=5.5 PHP_VERSIONS=7.2,7.3,7.4 ${CURRENT_DIR}/tester.sh
FIXTURE=laravel5.8 LARAVEL_VERSION=5.8 PHP_VERSIONS=7.2,7.3,7.4 ${CURRENT_DIR}/tester.sh
FIXTURE=laravel6   LARAVEL_VERSION=6   PHP_VERSIONS=7.2,7.3,7.4 ${CURRENT_DIR}/tester.sh
FIXTURE=laravel7   LARAVEL_VERSION=7   PHP_VERSIONS=7.2,7.3,7.4 ${CURRENT_DIR}/tester.sh
FIXTURE=laravel8   LARAVEL_VERSION=8   PHP_VERSIONS=7.3,7.4     ${CURRENT_DIR}/tester.sh
